// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOZAaSzsc5yjhC0kl5kCwtUIqe-HCTMmQ',
    appId: '1:355497080269:web:3b4962c5c76de362240084',
    messagingSenderId: '355497080269',
    projectId: 'health-5b3b1',
    authDomain: 'health-5b3b1.firebaseapp.com',
    storageBucket: 'health-5b3b1.firebasestorage.app',
    measurementId: 'G-D3NPYJYLDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk7CXoofyUq8ZlT3hLXKE6SNdvQJVgFMY',
    appId: '1:355497080269:android:13658bdb56aa694c240084',
    messagingSenderId: '355497080269',
    projectId: 'health-5b3b1',
    storageBucket: 'health-5b3b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcanY54YfdaRXyfvtTmldtIX4Bdt4Lh_k',
    appId: '1:355497080269:ios:c9435efa4fd99f68240084',
    messagingSenderId: '355497080269',
    projectId: 'health-5b3b1',
    storageBucket: 'health-5b3b1.firebasestorage.app',
    iosBundleId: 'com.example.medics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcanY54YfdaRXyfvtTmldtIX4Bdt4Lh_k',
    appId: '1:355497080269:ios:c9435efa4fd99f68240084',
    messagingSenderId: '355497080269',
    projectId: 'health-5b3b1',
    storageBucket: 'health-5b3b1.firebasestorage.app',
    iosBundleId: 'com.example.medics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOZAaSzsc5yjhC0kl5kCwtUIqe-HCTMmQ',
    appId: '1:355497080269:web:d2d527e2e829f678240084',
    messagingSenderId: '355497080269',
    projectId: 'health-5b3b1',
    authDomain: 'health-5b3b1.firebaseapp.com',
    storageBucket: 'health-5b3b1.firebasestorage.app',
    measurementId: 'G-KE7HGV6CKH',
  );
}
